# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-29 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LunBoTu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=20)),
                ('backColor', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tblunbotu',
            },
        ),
        migrations.CreateModel(
            name='ReMaiTu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mane', models.CharField(max_length=50)),
                ('tits', models.CharField(max_length=50)),
                ('price1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('img', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbremaitu',
            },
        ),
    ]
